### PR TITLE
Add query to debug logs in the most places where (assumed) that peopl…

### PR DESCRIPTION
**Pull request by karimcambridge**
…e get most errors

This way we don't have to turn on LOG_DEBUG if we have massive constant
MySQL usage!

### CODE REVIEW

**Comment by maddinat0r** [comment]
Thanks for the pull request!

Make sure there are no places left out where printing the query will help in finding an error (probably also in `GetFieldName`, `GetRowDataByName`, `mysql_pquery`, ...), because this will be the last pull request I'll ever merge into R39. R39-6 will be the last release in the R39 patch-release-series. 

You're also printing an unchecked char pointer in line 901, which will probably lead to a crash when executing `mysql_tquery(sql, "")`. Change it to something like `, query_str ? query_str : "");` and make sure that something like that doesn't get added by mistake again (eg. when you add more query-prints).

**Comment by maddinat0r** [comment]
@karimcambridge Are you still interested in that PR? I'm delaying the R39-6 release because of this PR.

**Comment by karimcambridge** [comment]
Lol yea yea sorry, too busy enjoying the summer. Will do it tmr hopefully.

**Comment by karimcambridge** [comment]
What do you think about that?

**Comment by maddinat0r** [comment]
Could you also print the query in `mysql_query`? Other than that, everything else seems fine.

**Comment by karimcambridge** [comment]
I can't find an obvious way of doing it in mysql_query.

mysql_query has no 'ERROR' level of debugging.

It only has this
```
if(!CMySQLHandle::IsValid(connection_id))
		return ERROR_INVALID_CONNECTION_HANDLE("mysql_query", connection_id);
```

**Comment by maddinat0r** [comment]
Ah yes, you've already added the query-print in `CMySQLQuery::Execute`, so it would be redundant to print the query again in `mysql_query`.
I'll merge this, thanks again!

**Pull request merged**
