### PR TITLE
Add pawn.json for sampctl version control

### PR DESCRIPTION
**Pull request by Southclaws**
This is an early version for testing, and since the MySQL plugin is probably one of the most used I figured I'd use it as the first live plugin for testing.

The format shouldn't change so I shouldn't need to pull any changes again!

### CODE REVIEW

**Comment by maddinat0r** [comment]
```regex
^mysql-.*-[Debian|CentOS].*$
```
Is this regex syntax? If yes, shouldn't these be parentheses instead of square brackets?
You should also add "Linux" to this, as my Debian releases are often meant for all other Linux distributions, so I probably will be doing only "CentOS" and "Linux" releases in the future.

And keep in mind that the CentOS and Linux releases differ slightly in the way the MySQL/MariaDB clients are linked (Linux is `/usr/lib/libmysqlclient.so` and CentOS is `/usr/lib/mysql/libmysqlclient.so`), thus people running for example Debian and using the CentOS release will probably encounter a "library not found" error on server start.

**Comment by Southclaws** [comment]
Ah, good catch yes those should be brackets.

And yeah the Centos thing is kind of an awkward situation for me. sampctl has a concept of operating systems but not individual distributions, I'm not sure if I want to introduce distribution checking into the tool. I always did wonder why there was a separate Centos release though, thanks for the clarification!

I'm going to try and figure out a good solution for this that doesn't rely too much on the package maintainer to add lots of special edge cases to their package definitions. I'm thinking of just allowing package *consumers* to specify a specific resource for their platform instead of trying to be clever and auto detecting it all.

**Comment by maddinat0r** [comment]
I think it's okay to let package maintainers specify this by themselves. I doubt that sampctl users would want to take care of this (package name changes -> every user has to adjust his config file vs. package name changes -> maintainer has to update package name once).

Try using the static release:
```regex
^mysql-.+-([Dd]ebian[0-9]|[Ll]inux)-static.*$
```
That one should work on most distributions out of the box without any problems.

**Comment by Southclaws** [comment]
So the static release is actually just for any distro, not debian? That would simplify things a lot, thanks!

**Comment by maddinat0r** [comment]
Yes, the static release has the MySQL/MariaDB client library statically linked (it's basically directly incorporated into the plugin file). This has the drawback that you can't use the latest client library distributed through your package manager, but I think that this is not really a huge concern for SA-MP server owners.

**Pull request merged**
